# this is to disable loading of custom JWT decoder from configuration
legendlime:
  local-validation: false


spring:
  security:
    oauth2:
      resourceserver:
# jwt must not be listed when introspection shall be supported
#        jwt:
#          issuer-uri: https://auth-service:8443/auth/realms/Demo
#          jwk-set-uri: https://auth-service:8443/auth/realms/Demo/protocol/openid-connect/certs

# introspection works as long as no jwt data is defined
        opaquetoken:
          introspection-uri: https://auth-service:8443/auth/realms/Demo/protocol/openid-connect/token/introspect
          client-id: demo-resource
          client-secret: ${DEMO-RS-CLIENT-SECRET}

logging:
  level:
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG
    

