spring:
  security:
    oauth2:
      resourceserver:
      
# jwt must not be listed when introspection shall be supported
#        jwt:
#          issuer-uri: https://map.legendlime.de/auth/realms/Demo
#          jwk-set-uri: https://map.legendlime.de/auth/realms/Demo/protocol/openid-connect/certs

# introspection works as long as no jwt data is defined
        opaquetoken:
          introspection-uri: https://map.legendlime.de/auth/realms/Demo/protocol/openid-connect/token/introspect
          client-id: demo-resource
          client-secret: ${DEMO-RS-CLIENT-SECRET}

logging:
  level:
    '[org.springframework.security.oauth2]': DEBUG
    

