server:
  port: 8090

# this is to disable loading of custom JWT decoder from configuration
legendlime:
  # must be set to true for security config to work
  oauth2:
    issuer-check: true
    add-realm: false
    client-id: demo-resource
  

spring:
  security:
    oauth2:
      resourceserver:
      
# jwt must not be listed when introspection shall be supported
        jwt:
          issuer-uri: https://auth-service:8443/auth/realms/Demo
          jwk-set-uri: https://auth-service:8443/auth/realms/Demo/protocol/openid-connect/certs
       

# introspection requires a different security configuration
#        opaquetoken:
#          introspection-uri: https://auth-service:8443/auth/realms/Demo/protocol/openid-connect/token/introspect
#          client-id: demo-resource
#          client-secret: ${DEMO-RS-CLIENT-SECRET}

logging:
  level:
    '[de.legendlime.demo]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG
    

