server:
  port: 8090

# this is to disable loading of custom JWT decoder from configuration
legendlime:
  # must be set to true for security config to work
  oauth2:
    issuer-check: true
    add-realm: false
    client-id: demo-resource
  

spring:
  application:
    name: ResourceServer

# demo DB coordinates
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/demo
    username: ${DEMO-RS-DB-USERNAME}
    password: ${DEMO-RS-DB-PASSWORD}


  security:
    oauth2:
      resourceserver:
      
# jwt must not be listed when introspection shall be supported
        jwt:
          issuer-uri: https://auth-service:8443/auth/realms/Demo
          jwk-set-uri: https://auth-service:8443/auth/realms/Demo/protocol/openid-connect/certs
       

# introspection requires a different security configuration
#        opaquetoken:
#          introspection-uri: https://auth-service:8443/auth/realms/Demo/protocol/openid-connect/token/introspect
#          client-id: demo-resource
#          client-secret: ${DEMO-RS-CLIENT-SECRET}


# Tracing configuration

  sleuth:
    sampler:
      probability: 1.0
    opentracing:
      enabled: true

  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    '[de.legendlime.demo]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG
    '[anoop.h.webflux]': DEBUG


